[pack]
name = "planned-work-jj"
schema = 2
version = "0.1.0"

[imports.work_planning]
source = "../../capabilities/work-planning"
export = true

[imports.work_implementation]
source = "../../capabilities/work-implementation"
export = true

[imports.vcs_jj_workspaces]
source = "../../substrates/vcs-jj-workspaces"
export = true
